### ISSUE TITLE
Crash on right click of City Center

### ISSUE THREAD

**Issue by Keoxxa** [fizechef/Unique-Dungeons-Release#2]
At the title says, right clicking on the City Center in an Ancient City causes a crash. 

https://pastebin.com/EmYz9zLG
Crash log.

[05:16:40] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'com.becks.interaction_boxes.common.predefinedInteractionBoxes.InteractionBox com.becks.uniquedungeons.common.blocks.cityCenterBlock.CityCenter.getPlayerSelection(java.util.Collection, net.minecraft.world.level.block.entity.BlockEntityType, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.player.Player, net.minecraft.world.phys.BlockHitResult)'
	at com.becks.uniquedungeons.common.blocks.cityCenterBlock.CityCenter.m_6227_(CityCenter.java:232) ~[uniquedungeons-0.70.3.1-47.2.0.jar%23652!/:0.70.3]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23682!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[05:16:42] [Server thread/INFO]: Stopping server

Log error.

https://pastebin.com/eNse0Aca
Part 1 of full log.

https://pastebin.com/dgnnBnWq
Part 2 of full log.

This is a rough, unrefined modpack I'm making at the moment. No issues with random crashing so far, but this is a consistent, always crash upon right clicking the City Center block in the Ancient City Dungeon. There is nothing on the pedestals around it, and my hands are empty.  I am running on a single player world.
I am using the latest versions of both the interaction boxes mod and this mod.

**Comment by fizechef** [comment]
I have investigated and found this crash resulted from an oversight when we switched from Interaction Boxes 0.692 to 0.693 

This should be resolved in Unique Dungeons 0.70.3.2

Huge thanks for making us aware of this issue.
